name: Issue → n8n
on:
  issues:
    types: [opened, edited, reopened, closed]
permissions:
  contents: read
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping n8n with HMAC
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
          N8N_WEBHOOK_SECRET: ${{ secrets.N8N_WEBHOOK_SECRET }}
        run: |
          set -euo pipefail
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          NUM=$(jq -r .issue.number "$GITHUB_EVENT_PATH")
          TITLE=$(jq -r .issue.title "$GITHUB_EVENT_PATH")
          BODYTXT=$(jq -r .issue.body "$GITHUB_EVENT_PATH")
          BODY=$(jq -n \
            --arg ts "$TS" \
            --arg event "$GITHUB_EVENT_NAME" \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg action "$GITHUB_ACTION" \
            --arg title "$TITLE" \
            --arg body "$BODYTXT" \
            --arg user "$GITHUB_ACTOR" \
            --argjson number "$NUM" \
            "{ts:$ts,event:$event,repo:$repo,action:$action,issue:{number:$number,title:$title,body:$body},actor:$user}")
          SIG="sha256=$(printf "%s" "$BODY" | openssl dgst -sha256 -hmac "$N8N_WEBHOOK_SECRET" -binary | xxd -p -c 256)"
          CODE=$(curl -s -o /tmp/n8n_issue.json -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -H "X-Timestamp: $TS" \
            -H "X-Signature: $SIG" \
            --data "$BODY" "$N8N_WEBHOOK_URL" || true)
          echo "n8n HTTP=$CODE"
          test "$CODE" = "200" -o "$CODE" = "202"
