name: Notify n8n (GitHub Workflows)
on:
  workflow_run:
    workflows: ["**"]
    types: [requested, in_progress, completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify n8n Webhook
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
          N8N_WEBHOOK_SECRET: ${{ secrets.N8N_WEBHOOK_SECRET }}
        run: bash .github/scripts/ping_n8n.sh
