name: rotate n8n secret (quarterly)
on:
  schedule: [{ cron: "0 3 1 */3 *" }]
  workflow_dispatch: {}
jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - id: gen
        run: |
          NEW=$(openssl rand -hex 32)
          echo "secret=$NEW" >> $GITHUB_OUTPUT
      - env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: gh secret set N8N_WEBHOOK_SECRET -b "${{ steps.gen.outputs.secret }}"
