name: sync_status_to_pages
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - ".status/**"
permissions: { contents: write }
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare docs/status/data.json
        run: |
          mkdir -p docs/status
          if [ -s .status/heartbeat_status.json ]; then
            cp -f .status/heartbeat_status.json docs/status/data.json
          else
            TS=$(date -u +%FT%TZ)
            printf "{\"ok\":false,\"http\":0,\"timestamp\":\"%s\",\"source\":\"bootstrap\"}\n" "$TS" > docs/status/data.json
          fi
      - name: Commit data.json if changed
        run: |
          git config user.email actions@github.com
          git config user.name github-actions
          git add docs/status/data.json || true
          git commit -m "chore(pages): refresh data.json" || true
          git push || true
